services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    
    environment:
      PGADMIN_DEFAULT_EMAIL: aman@example.com
      PGADMIN_DEFAULT_PASSWORD: aman
    ports:
      - "5050:80"


  backend:
    build: .
    container_name: backend_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
       - db
    environment:
         DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
         DJANGO_SECRET_KEY: ${SECRET_KEY}
         DEBUG: "True"

    volumes:
      - .:/app

volumes:
  postgres-data:  

      
        