# Generated by Django 5.1.4 on 2024-12-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
                ('role_description', models.CharField(max_length=200)),
                ('hourly_wage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_location', models.CharField(max_length=200)),
                ('site_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Construction', 'Under Construction')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('join_date', models.DateField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.role')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no_of_hours', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.sites')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('present', 'Present'), ('leave', 'Leave')], max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.sites')),
            ],
        ),
    ]
