# Generated by Django 5.1.4 on 2024-12-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='employeeattendance',
            table='employee_attendance',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='siteattendance',
            table='site_attendance',
        ),
        migrations.AlterModelTable(
            name='sites',
            table='sites',
        ),
    ]
