# Generated by Django 5.1.4 on 2024-12-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_siteattendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteattendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeAttendance',
        ),
    ]
